### ISSUE TITLE
AO Rev Bug - Slig walks into the left wall instead of going to the next screen to the right

### ISSUE THREAD

**Issue by mouzedrift** [AliveTeam/alive_reversing#1059]
Steps to repro:
- load the save
- check the video for further instructions 👀 

https://user-images.githubusercontent.com/43358824/105606363-3aa1e500-5d99-11eb-9fb6-211e66e877a8.mp4

save: 
[!.zip](https://github.com/AliveTeam/alive_reversing/files/5860417/default.zip)

function: ``SligSpawner::VUpdate_4028A0``

**Comment by paulsapps** [comment]
This is an OG issue caused by using random initialized memory in `Slig::field_13C_zone_rect` in newer memory allocators sometimes these values for the rect x and w members are zero or near zero which makes 

```
 if (IsFacingEffectiveLeft_46BD70(this) && (field_A8_xpos - (ScaleToGridSize_41FA30(field_BC_sprite_scale) * FP_FromInteger(2))) <= FP_FromInteger(field_13C_zone_rect.x))
 ```
 
 not get hit in `void Slig::WaitOrWalk_46E440()`

Best we can do is hack the values of `field_13C_zone_rect` to something that works for this slig in the case where x/w are not set in `void Slig::Init_46B890()` and raise an OG bug to fix the map not having a left/right bound object for this spawned slig.
